### ISSUE TITLE
How hard would it be to introduce union types / optional types? 

### ISSUE THREAD

**Issue by mindreframer** [ExpressApp/construct#22]
Came across `construct` and it looks pretty solid!

Would you be interested in adding some additional features to support more advanced type modelling, like union types / optional types? 

A bit like the following contrived example: 

```elixir
defmodule Post do
  use Construct do
    field :title
    field :author, {:oneof, [User, Bot]}
    field :comments, {:array, Comment}
  end
end
```

**Comment by artemeff** [comment]
> Came across construct and it looks pretty solid!

Thank you! :)

> Would you be interested in adding some additional features to support more advanced type modelling, like union types / optional types?

Yeah, I'm thinking about it, but there's several problems. Suppose you have some simple modules:

```elixir
defmodule User do
  use Construct do
    field :id, :integer
    field :name
    field :age, :integer
  end
end

defmodule Bot do
  use Construct do
    field :id, :integer
    field :name
    field :version
  end
end
```

We can make custom type with function clause for all required fields to match union type, like this:

```elixir
defmodule Post do
  use Construct do
    field :author, {:oneof, [User, Bot]} # custom type dynamically defines here, like Post.AuthorUnion
  end
end

defmodule Post.AuthorUnion do
  def type(%{id: _, name: _, age: _}), do: User
  def type(%{id: _, name: _, version: _}), do: Bot
  def type(_), do: :error
end
```

But there's problem when you have equal set of fields in union type; and I don't know what to do with optional fields (that have default values).

Union typing is hard, but I have tiny and a little-bit tricky solution that works :)

```elixir
defmodule Author do
  @behaviour Construct.Type

  # here's the trick, just choose the type by yourself, based on keys or value in specific field.
  # but be careful, because there can be atoms and strings in keys!
  def cast(%{"age" => _} = v), do: User.make(v)
  def cast(%{"version" => _} = v), do: Bot.make(v)
  def cast(_), do: :error
end

defmodule Post do
  use Construct do
    field :author, Author # use custom type!
  end
end
```

```elixir
iex> Post.make(%{"author" => %{}})
{:error, %{author: :invalid}}

iex>  Post.make(%{"author" => %{"age" => "420"}})
{:error, %{author: %{id: :missing, name: :missing}}}

iex> Post.make(%{"author" => %{"id" => "42", "name" => "john doe", "age" => "420"}})
{:ok, %Post{author: %User{age: 420, id: 42, name: "john doe"}}}

iex> Post.make(%{"author" => %{"id" => "42", "name" => "john doe", "version" => "1.0.0"}})
{:ok, %Post{author: %Bot{id: 42, name: "john doe", version: "1.0.0"}}}
```

**Comment by mindreframer** [comment]
Wow! That's a neat trick! This might be enough for simple needs. Maybe put it in the readme under tricky / advanced section for other developers. 


Thank you! You can close this issue or leave it as reference. 

Cheers!
